# Generated by Django 3.1.1 on 2020-10-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
